version: '3.8'

services:
  mariadb:
    platform: linux/amd64
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    restart: always

  phpmyadmin:
    platform: linux/amd64
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    restart: always

volumes:
  data:

